### ISSUE TITLE
Update README.md with install steps

### ISSUE THREAD

**Issue by arnikz** [au-research/raido#7]
Please document steps needed to install/configure the software for local testing (pref. non-AWS).

**Comment by ardc-shorn** [comment]
There will be a new "local dev" document added under /doc - a single place with a set of linear steps to get the software running on a developer's machine.  It will likely not contain anything but summarisation and links to the various other readme files that document getting stuff running on a dev machine.

Additionally, an "installation" document (or maybe "deployment" would be  better name) will be added that will outline what the deployment process would be expected to look like in a theoretical "simple deployment" configuration.  This file, at least initially, will be very abstract - since we don't have any plans to deploy Raido outside of AWS.

**Comment by ardc-shorn** [comment]
https://github.com/au-research/raido-v2/blob/main/doc/local-development.md

**Comment by arnikz** [comment]
Thank you. This is a good starting point. However, I'm wondering if you could provide a _recipe_ (e.g., using `docker-compose`) that includes the entire software stack in Docker-ized form (in addition to this [Dockerfile](https://github.com/au-research/raido-v2/blob/main/api-svc/docker/src/main/docker/Dockerfile)).

**Comment by ardc-shorn** [comment]
The current Raido codebase is not intended as a turn-key installable solution.
There is a plan to create a fully standalone/installable solution, but work on that is not intended to be begun for years yet (and there's no funding for it currently).

There is now full documentation of the operational and deployment environments currently used by the ARDC to operate Raido as the "ARDC RAiD Service" for Oceania.

* https://github.com/au-research/raido/blob/main/doc/architecture/environment/operational-environment.md
* https://github.com/au-research/raido/blob/main/doc/architecture/environment/deployment-environment.md

The AWS CDK code in the https://github.com/au-research/raido-v2-aws-private/ repository is an exact recipe for running Raido on AWS - this is guaranteed since it _is_ the codebase we use to run the service.

Request access to the AWS repository via an email to `contact@raid.org` or contact a raid team member.
We will add you to the [AWS Repo View Only](https://github.com/orgs/au-research/teams/aws-repo-view-only) team so you can follow the links in the doco if desired.

This new environmental operational/deployment documentation has been linked from the root readme.md file ("Environments" section).
